version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devTT_postgres
    expose: [5432]
    environment:
      - POSTGRES_DB=devTT
      - POSTGRES_USER=devTT
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    networks:
      devTT_network:
        aliases:
          - postgres

  api:
    image: openjdk:21-jdk
    container_name: devTT_api
    working_dir: /api
    expose: [8080]
    env_file: .env
    volumes:
      - .:/api
    command: sh -c "cd /api && ./mvnw package && java -jar target/*.jar"
    networks:
      devTT_network:
        aliases:
          - api
    depends_on:
      postgres:
          condition: service_started
      mongo:
          condition: service_started

  proxy:
    build: ./nginx
    image: nginx:stable
    container_name: devTT_proxy
    hostname: nginx
    ports:
      - "8081:80"
    networks:
      devTT_network:
        aliases:
          - proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      api:
        condition: service_started

networks:
  devTT_network:
    name: devTT_network
    driver: bridge

volumes:
  postgres_data:
    name: devTT_postgres_data