version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devTT_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=devTT
      - POSTGRES_USER=devTT
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
      devTT_network:
        aliases:
          - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devTT" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    build:
      context: ./rabbit
    container_name: devTT_rabbitmq
    restart: unless-stopped
    environment:
        - RABBITMQ_DEFAULT_USER=devTT
        - RABBITMQ_DEFAULT_PASS=123
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbit/rabbit-definitions.json:/etc/rabbitmq/definitions.template.json
      - ./rabbit/init.sh:/usr/local/bin/setup_rabbitmq.sh
    entrypoint: [ "/bin/bash", "/usr/local/bin/setup_rabbitmq.sh" ]
    networks:
        devTT_network:
            aliases:
            - rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl node_health_check" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
        context: .
        dockerfile: Dockerfile-local
    container_name: devTT_api
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/api
      - ~/.m2:/root/.m2
    ports:
      - "8081:8080"
      - "35729:35729"
      - "5005:5005"
    networks:
      devTT_network:
        aliases:
          - api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  devTT_network:
    name: devTT_network
    driver: bridge

volumes:
  postgres_data:
    name: devTT_postgres_data