version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devTT_postgres
    expose: [5432]
    environment:
      - POSTGRES_DB=devTT
      - POSTGRES_USER=devTT
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    networks:
      devTT_network:
        aliases:
          - postgres

networks:
  devTT_network:
    name: devTT_network
    driver: bridge

volumes:
  postgres_data:
    name: devTT_postgres_data