version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: devTT_postgres
    expose: [5432]
    environment:
      - POSTGRES_DB=devTT
      - POSTGRES_USER=devTT
      - POSTGRES_PASSWORD=123
    ports:
      - "5433:5432"
    networks:
      devTT_network:
        aliases:
          - postgres

  mongo:
    image: mongo:5
    container_name: devTT_mongo
    expose: [27017]
    environment:
      - MONGO_INITDB_DATABASE=devTT
      - MONGO_INITDB_USERNAME=devTT
      - MONGO_INITDB_PASSWORD=123
    ports:
      - "27018:27017"
    networks:
      devTT_network:
        aliases:
          - mongo

networks:
  devTT_network:
    name: devTT_network
    driver: bridge

volumes:
  postgres_data:
    name: devTT_postgres_data
  mongo_data:
    name: devTT_mongo_data