name: Auto Approve and Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  checks: read

jobs:
    auto-approve:
        runs-on: ubuntu-latest

        steps:
            - name: Wait for all checks to pass
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      if (context.payload.pull_request.draft) {
                          core.setFailed('Pull request is a draft.');
                      }
                    
                      console.log("Esperando todas as verificações passarem...");
                    
                      const { data: checks } = await github.checks.listForRef({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          ref: context.payload.pull_request.head.sha
                      });
                    
                      const nonPassingChecks = checks.check_runs.filter(check => check.conclusion !== 'success' && check.status !== 'completed');
                    
                      if (nonPassingChecks.length > 0) {
                          core.setFailed('As verificações configuradas para este pull request não foram aprovadas.');
                      }
                    
                      console.log("Todas as verificações passaram.")

            - name: Auto approve pull request
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      console.log("Aprovando pull request...");
                    
                      await github.pulls.createReview({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.payload.pull_request.number,
                          event: 'APPROVE',
                          body: 'Pull request aprovado automaticamente pelo GitHub Actions após a conclusão de todas as verificações.'
                      });
                    
                      console.log("Pull request aprovado.")

            - name: Auto merge pull request
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      console.log("Mesclando pull request...");
                    
                      await github.pulls.merge({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: context.payload.pull_request.number,
                          sha: context.payload.pull_request.head.sha,
                          merge_method: 'squash',
                          commit_title: context.payload.pull_request.title + ' (#' + context.payload.pull_request.number + ')'
                          commit_message: context.payload.pull_request.body
                      });
                    
                      console.log("Pull request mesclado.")

            - name: Auto delete branch
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      console.log("Deletando branch...");
                    
                      await github.git.deleteRef({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          ref: 'heads/' + context.payload.pull_request.head.ref
                      });
                    
                      console.log("Branch deletada.")