name: Build and Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Project

    steps:
      - uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Extract Java version from pom.xml
        run: |
          JAVA_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="java.version"]/text()' pom.xml)
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Check Test Coverage
        run: |
          COVERED_INSTRUCTIONS=$(xmllint --xpath "sum(//package[matches(@name, 'br/com/devtt/.*/application/(services|usecases|factories|strategies)')]/counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED_INSTRUCTIONS=$(xmllint --xpath "sum(//package[matches(@name, 'br/com/devtt/.*/application/(services|usecases|factories|strategies)')]/counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          TOTAL_INSTRUCTIONS=$((COVERED_INSTRUCTIONS + MISSED_INSTRUCTIONS))
          PERCENTAGE=$(echo "scale=2; $COVERED_INSTRUCTIONS * 100 / $TOTAL_INSTRUCTIONS" | bc)
          echo "$PERCENTAGE% Test Coverage $TOTAL_INSTRUCTIONS instructions"
          echo "Packages: br/com/devtt/core/application/services and br/com/devtt/core/application/usecases"
          if (( $(echo "$PERCENTAGE < 80" | bc -l) )); then
            echo "Error: Test coverage is below 80%."
            exit 1
          else
            echo "Success: Test coverage is over 80%."
          fi