name: Build and Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Project

    steps:
      - uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Extract Java version from pom.xml
        run: |
          JAVA_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="properties"]/*[local-name()="java.version"]/text()' pom.xml)
          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Check Test Coverage
        run: |
          COVERED_INSTRUCTIONS=$(xmllint --xpath "sum(//package[contains(@name, 'br/com/devtt/') and contains(@name, '/application/') and (contains(@name, 'services') or contains(@name, 'usecases') or contains(@name, 'factories') or contains(@name, 'strategies'))]/counter[@type='INSTRUCTION']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED_INSTRUCTIONS=$(xmllint --xpath "sum(//package[contains(@name, 'br/com/devtt/') and contains(@name, '/application/') and (contains(@name, 'services') or contains(@name, 'usecases') or contains(@name, 'factories') or contains(@name, 'strategies'))]/counter[@type='INSTRUCTION']/@missed)" target/site/jacoco/jacoco.xml)
          TOTAL_INSTRUCTIONS=$(echo "$COVERED_INSTRUCTIONS + $MISSED_INSTRUCTIONS" | bc)
          PERCENTAGE=$(echo "scale=2; $COVERED_INSTRUCTIONS * 100 / $TOTAL_INSTRUCTIONS" | bc)
          echo "$PERCENTAGE% de Cobertura de Teste em $TOTAL_INSTRUCTIONS instruções"
          echo "Pacotes: br/com/devtt/core/application/services e br/com/devtt/core/application/usecases"
          if (( $(echo "$PERCENTAGE < 80" | bc -l) )); then
            echo "Erro: A cobertura de testes está abaixo de 80%."
            exit 1
          else
            echo "Sucesso: A cobertura de testes está acima de 80%."
          fi